# Generated by Django 4.0.4 on 2022-04-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('pricechange', models.IntegerField()),
            ],
        ),
    ]
